# Generated by Django 4.2.7 on 2023-12-25 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserApiUser',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=64, unique=True)),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'user_api_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('pid2', models.IntegerField(null=True)),
                ('score1', models.IntegerField(null=True)),
                ('score2', models.IntegerField(null=True)),
                ('startTime', models.DateField(auto_now_add=True)),
                ('endTime', models.DateField(auto_now=True)),
                ('pid1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='offline.userapiuser')),
            ],
        ),
    ]
