# Generated by Django 4.2.7 on 2023-12-25 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offline', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('tid', models.AutoField(primary_key=True, serialize=False)),
                ('startTime', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='game',
            name='pid1',
        ),
        migrations.RemoveField(
            model_name='game',
            name='pid2',
        ),
        migrations.RemoveField(
            model_name='game',
            name='score1',
        ),
        migrations.RemoveField(
            model_name='game',
            name='score2',
        ),
        migrations.CreateModel(
            name='PlayerMatch',
            fields=[
                ('matchId', models.AutoField(primary_key=True, serialize=False)),
                ('score', models.IntegerField(null=True)),
                ('gid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='offline.game')),
                ('pid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='offline.userapiuser')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='tid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='offline.tournament'),
        ),
    ]
