version: "3"
services:
    server:
        build: ./server
        image: nginx
        container_name: nginx
        restart: on-failure
        volumes:
            - ../srcs/main_app/static/:/vol/static
            - ../srcs/user_app/media/:/vol/media
        ports:
            - "80:80"
            - "443:443"
            - "8001:8001"
            - "8004:8004"
            - "8002:8002"
            - "8003:8003"
            - "8005:8005"
        depends_on:
            - mainapp
            - userapp
            - tourapp
            - gameapp
            - friendsapp
        networks:
            - user_app_network
        environment:
            - DEBUG=0

    mainapp:
        build: 
          context: ../
          dockerfile: ./docker_srcs/main_app/Dockerfile.prod
        image: mainapp
        container_name: mainapp
        restart: on-failure
        expose:
          - 8000
        depends_on:
            postgres:
                condition: service_healthy
            userapp:
                condition: service_started
            gameapp:
                condition: service_started
            tourapp:
                condition: service_started
        env_file:
            - ./.env
        networks:
            - user_app_network
        environment:
            - DEBUG=0
 
    gameapp:
        build: 
          context: ../
          dockerfile: ./docker_srcs/game_app/Dockerfile.prod
        image: gameapp
        container_name: gameapp
        restart: on-failure
        expose:
          - 8003
        depends_on:
            userapp:
                condition: service_healthy
            tourapp:
                condition: service_healthy
        env_file:
            - ./.env
        networks:
            - user_app_network
        environment:
            - DEBUG=0

    tourapp:
        build: 
          context: ../
          dockerfile: ./docker_srcs/tour_app/Dockerfile.prod
        image: tourapp
        container_name: tourapp
        restart: on-failure
        expose:
          - 8004
        depends_on:
            postgres:
                condition: service_healthy
        env_file:
            - ./.env
        networks:
            - user_app_network
        healthcheck:
            test: ["CMD", "curl", "--fail", "http://localhost:8004/tour/health"]
            interval: 5s
            timeout: 5s
            retries: 5

    userapp:
        build:
          context: ../
          dockerfile: ./docker_srcs/user_app/Dockerfile.prod
        image: userapp
        container_name: userapp
        restart: on-failure
        expose:
          - 8001
        depends_on:
            postgres:
                condition: service_healthy
        env_file:
            - ./.env
        volumes:
            - ../srcs/user_app/media:/home/user_app/media
        networks:
            - user_app_network
        healthcheck:
            test: ["CMD", "curl", "--fail", "http://localhost:8001/api/health"]
            interval: 5s
            timeout: 5s
            retries: 5
        environment:
            - DEBUG=0

    postgres:
        build: ./postgres
        image: postgres
        container_name: postgres
        restart: on-failure
        volumes:
            - ../srcs/postgres/data:/var/lib/postgresql/data
        healthcheck:
            test: pg_isready -U postgres
            interval: 5s
            timeout: 5s
            retries: 5
        env_file:
            - ./.env
        networks:
            - user_app_network
        environment:
            - DEBUG=0

    friendsapp:
        build:
          context: ../
          dockerfile: ./docker_srcs/friends_app/Dockerfile.prod
        image: friendsapp
        container_name: friendsapp
        restart: always
        expose:
          - 8002
        depends_on:
            postgres:
                condition: service_healthy
            userapp:
                condition: service_healthy
        env_file:
            - ./.env
        networks:
            - user_app_network
        environment:
            - DEBUG=0

networks:
    user_app_network:
        driver: bridge
