version: "3"
services:
    server:
        build: ./server
        restart: always
        ports:
            - "80:80"
        depends_on:
            - main_app
            - postgres

    main_app:
        build: ./main_app
        restart: always
        volumes:
            - main_app_data:/var
        depends_on:
            - postgres
            - auth_app

    auth_app:
        build: ./auth_app
        restart: always
        volumes:
            - auth_app_data:/var
        depends_on:
            - postgres

    postgres:
        build: ./postgres
        restart: always
        volumes:
            - postgres_data:/var/lib/postgresql/data

volumes:
    main_app_data:
        driver: local
        driver_opts:
            o: bind
            type: none
            device: ../srcs/main_app

    auth_app_data:
        driver: local
        driver_opts:
            o: bind
            type: none
            device: ../srcs/main_app/auth_app/

    postgres_data:
        driver: local
        driver_opts:
            o: bind
            type: none
            device: ../srcs/postgres/data
