version: "3"
services:
    server:
        build: ./server
        restart: always
        ports:
            - "80:80"
        depends_on:
            - mainapp
            - postgres

    mainapp:
        build: ./main_app
        restart: always
        ports:
            - "8000:8000"
        networks:
            - user_app_network
        # command:
        # - sh
        # - -c
        # - |
        #   python manage.py makemigrations
        #   python manage.py migrate --noinput
        #   python manage.py runserver 0.0.0.0:8000
        volumes:
            - main_app_data:/home/main_app
        depends_on:
            userapp:
                condition: service_started
            postgres:
                condition: service_healthy
        env_file:
            - ./.env

    userapp:
        build: ./user_app
        restart: always
        ports:
            - "8001:8000"
        volumes:
            - user_app_data:/home/user_app
        depends_on:
            postgres:
                condition: service_healthy
        env_file:
            - ./.env
        networks:
            - user_app_network

    friendsapp:
        build: ./friends_app
        restart: always
        ports:
            - "8002:8000"
        volumes:
            - friends_app_data:/home/friends_app
            - user_app_data:/home/user_app
        depends_on:
            postgres:
                condition: service_healthy
        env_file:
            - ./.env
        networks:
            - user_app_network

    postgres:
        build: ./postgres
        restart: always
        volumes:
            - postgres_data:/var/lib/postgresql/data
        healthcheck:
            test: pg_isready -U postgres
            interval: 5s
            timeout: 5s
            retries: 5
        environment:
            - POSTGRES_DB=${USER_DB_NAME}
            - POSTGRES_USER=${USER_DB_USER}
            - POSTGRES_PASSWORD=${USER_DB_PASS}
        env_file:
            - ./.env
        networks:
            - user_app_network

volumes:
    main_app_data:
        driver: local
        driver_opts:
            o: bind
            type: none
            device: ../srcs/main_app/

    user_app_data:
        driver: local
        driver_opts:
            o: bind
            type: none
            device: ../srcs/user_app/
    
    friends_app_data:
        driver: local
        driver_opts:
            o: bind
            type: none
            device: ../srcs/friends_app/

    postgres_data:
        driver: local
        driver_opts:
            o: bind
            type: none
            device: ../srcs/postgres/data

networks:
    user_app_network:
        driver: bridge
